# Definimos que imagen vamos a utilizar como base
FROM alpine:3.7

# Definimos el entrypoint o comando que se va a utilizar al iniciar la instancia
ENTRYPOINT ["echo"]

# Definimos los parámetros que se añadiran al entrypoing cuando se inicie la instancia
CMD ["Hello VigoJUG!"]
